### ISSUE TITLE
How many epoches you have trained to achieve your training results? 

### ISSUE THREAD

**Issue by arceus-jia** [jiyegege/AnimeGANv2_Tensorflow2#1]
Thank you very much for your work, I did some attempts to convert from animeganv2_tf1 to tf2 before but failed. 
But there is a question I want to ask. How many epochs you have trained to achieve your training results? 
My results after 400 epochs are still poor, I don't know if it's a configuration issue or something else.
![1](https://user-images.githubusercontent.com/5162767/177892244-3157e91f-9f5b-4b95-9fa1-ec4a0a496574.jpg)

**Comment by jiyegege** [comment]
I trained 97 epochs to get the results mentioned in my readme. From the image you sent, it seems that the problem is not in your hyperparameter configuration, but most likely in your training code or model structure. I usually train up to 40 epochs before the anime style appears.
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/26988300/177896527-baaf02bc-106b-435b-8c04-d71a64a020ad.png">

**Comment by arceus-jia** [comment]
> I trained 97 epochs to get the results mentioned in my readme. From the image you sent, it seems that the problem is not in your hyperparameter configuration, but most likely in your training code or model structure. I usually train up to 40 epochs before the anime style appears. <img alt="image" width="1705" src="https://user-images.githubusercontent.com/26988300/177896527-baaf02bc-106b-435b-8c04-d71a64a020ad.png">

Thanks for your reply,I use your code directly and did not modify training code and model structure.  Is there a requirement for cudnn and cuda versions?  my cudnn is 8.1.0.77 and cudatoolkit is 11.2.2, and my gpu is rtx3090

**Comment by jiyegege** [comment]
> > I trained 97 epochs to get the results mentioned in my readme. From the image you sent, it seems that the problem is not in your hyperparameter configuration, but most likely in your training code or model structure. I usually train up to 40 epochs before the anime style appears. <img alt="image" width="1705" src="https://user-images.githubusercontent.com/26988300/177896527-baaf02bc-106b-435b-8c04-d71a64a020ad.png">
> 
> Thanks for your reply,I use your code directly and did not modify training code and model structure. Is there a requirement for cudnn and cuda versions? my cudnn is 8.1.0.77 and cudatoolkit is 11.2.2, and my gpu is rtx3090

My cuda version is 11.2 and cudnn is 8.2.1

**Comment by arceus-jia** [comment]
well I've found the issue. 
in test.py line 40
saver should be "tf.train.Checkpoint(generated=test_generated)"
not "tf.train.Checkpoint()"

**Comment by jiyegege** [comment]
> 

Thank you for your feedback, my side has been using test2.py, test.py is directly using the tf1 version of the original author, test file I am still in the process of improving
