### ISSUE TITLE
About style loss

### ISSUE THREAD

**Issue by JJASMINE22** [jiyegege/AnimeGANv2_Tensorflow2#2]
According to the generator's style loss provided by https://github.com/TachibanaYoshino/AnimeGANv2/blob/617ab10ce21877df90c9cf2b705712bc81b1e2e6/tools/ops.py
Maybe function gram() should be expressed like:

    feat = tf.linalg.einsum('bijc,bijd->bcd', x, x)
    num_locations = tf.math.reduce_prod(x.shape[1:])
    num_locations = tf.cast(num_locations, dtype=tf.float32)

    feat = feat/num_locations

Otherwise, it may cause generator gradient explosion, and difficult to achieve Antagonism effect

**Comment by jiyegege** [comment]
Thanks for your issue, I did find the gradient explosion problem after replacing the backstone, now I used your code to train again and it did solve the problem, the loss curve is also normal compared to before.
before:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/26988300/208795390-6fb2632c-abf1-455f-adf9-7856d99b5e46.png">
after:
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/26988300/208795544-4baaf342-41d8-475f-a22c-b656b6ddd1c8.png">
