### ISSUE TITLE
你好，我看这个工程里面数据来自于wandb，数据集可以共享一下吗

### ISSUE THREAD

**Issue by ldh127** [jiyegege/AnimeGANv2_Tensorflow2#3]

**Comment by jiyegege** [comment]
我这边并没有使用特别的数据集，就是使用原作者的[数据集](https://github.com/TachibanaYoshino/AnimeGAN/releases/tag/dataset-1)而已

**Comment by jiyegege** [comment]
@ldh127 我这边并没有使用特别的数据集，就是使用原作者的[数据集](https://github.com/TachibanaYoshino/AnimeGAN/releases/tag/dataset-1)而已

**Comment by ldh127** [comment]
大佬，你达到你这个训练效果的参数能分享一下吗，我用你的默认参数训练了20个epoch，怎么特别模糊，效果很差，用的是 config/default.yaml 那个文件的配置

**Comment by jiyegege** [comment]
@ldh127 何种数据集，推荐何种参数，default文件里面都有
<img width="604" alt="image" src="https://github.com/jiyegege/AnimeGANv2_Tensorflow2/assets/26988300/1ec79ee3-d8c8-4938-919a-5fd4b33f4e1a">

**Comment by ldh127** [comment]
你是直接用这这个命令跑的吗&nbsp;python train.py --config_path config/config-defaults.yaml --dataset Hayao --hyperparameters False，直接跑20 个 epoch 可以达到你read.md说明里的那个效果吗 ，为啥我用这个跑出来的效果特别差，基本上就属于用不了，有用别的训练策略吗


ldh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiyegege/AnimeGANv2_Tensorflow2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jiyegege/AnimeGANv2_Tensorflow2] 你好，我看这个工程里面数据来自于wandb，数据集可以共享一下吗 (Issue #3)





 
@ldh127 何种数据集，推荐何种参数，default文件里面都有

**Comment by jiyegege** [comment]
@ldh127 20个epoch不太够，我一般都是100个epoch，而且中间调整了一次模型代码和bug，复现效果好的话，还得看我另外一个pytorch的版本

**Comment by ldh127** [comment]
@jiyegege  pytorch版本里，根据你代码的参数，虽然也是hayao数据集，但是 config-default 里的参数比config-ini里面多一些，然后我看数据集虽然是hayao，但是参数有的用了 Shinkai 的参数，是这样效果能达到更好吗

**Comment by jiyegege** [comment]
@ldh127 config-init.yaml是用来预训练的warm up模型的，他训练出来的checkpoint可以在后面正式训练中使用，所以预训练的数据集选择影响不大，选择同样的数据集和参数可能还是能够加快模型收敛的
